name: flutter_hooks
description: A flutter implementation of React hooks. It adds a new kind of widget with enhanced code reuse.
homepage: https://github.com/rrousselGit/flutter_hooks
author: Remi Rousselet <darky12s@gmail.com>

version: 0.5.0

environment:
  sdk: ">=2.0.0 <3.0.0"
  # flutter: ">=1.0.0 < 1.5.8"

dependencies:
  flutter_web: any
  flutter_web_ui: any


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
